## Part 1 - Data Preparation and Exploration

In [1]:
%%capture
# Due to the configuration of the base Jupter image, the following imports are required for the regressions in the assignment to report the correct metrics

import sys 
!{sys.executable} -m pip uninstall statsmodels --yes 
!{sys.executable} -m pip uninstall numpy --yes
!{sys.executable} -m pip uninstall pandas --yes 
!{sys.executable} -m pip uninstall patsy --yes 
!{sys.executable} -m pip install numpy==1.17
!{sys.executable} -m pip install pandas==1.0
!{sys.executable} -m pip install patsy==0.5.2
!{sys.executable} -m pip install statsmodels==0.11.1

In [2]:
#Import Libraries

import pandas as pd
import datetime as dt
import scipy.stats as sp
import numpy as np
import statsmodels.formula.api as sm

In [3]:
# Import Shotlog_14_15 and Player_Stats Datasets

Shotlog_1415=pd.read_csv("Assignment Data/Week 6/Shotlog_14_15.csv")
Player_Stats=pd.read_csv("Assignment Data/Week 6/Player_Stats_14_15.csv")
display(Shotlog_1415)

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,...,closest_defender,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit,shot_count,shot_per_game
0,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,1,1,...,"Lopez, Brook",201572,6.6,1,2,al horford,201143,0.541259,715,10
1,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,2,1,...,"Lopez, Brook",201572,5.6,0,0,al horford,201143,0.541259,715,10
2,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,3,1,...,"Lopez, Brook",201572,4.7,0,0,al horford,201143,0.541259,715,10
3,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,4,1,...,"Lopez, Brook",201572,5.8,0,0,al horford,201143,0.541259,715,10
4,21400280,5-Dec-14,ATL @ BKN,BKN,ATL,A,W,23,5,2,...,"Lopez, Brook",201572,6.4,0,0,al horford,201143,0.541259,715,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128064,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,11,3,...,"Burke, Trey",203504,4.7,1,2,john wall,202322,0.448513,874,15
128065,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,12,3,...,"Exum, Dante",203957,3.4,1,2,john wall,202322,0.448513,874,15
128066,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,13,4,...,"Kanter, Enes",202683,1.2,0,0,john wall,202322,0.448513,874,15
128067,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,14,4,...,"Kanter, Enes",202683,1.4,1,2,john wall,202322,0.448513,874,15
128068,21400350,14-Dec-14,WAS vs. UTA,WAS,UTA,H,W,9,15,4,...,"Burke, Trey",203504,4.0,0,0,john wall,202322,0.448513,874,15

In [4]:
# Convert the “date” variable to a date type variable and calculate summary statistics for the “shot_clock” variable.

#Date variable conversion
Shotlog_1415['date']=pd.to_datetime(Shotlog_1415['date'])
Shotlog_1415['date'].describe()

count                  128069
unique                    120
top       2015-01-07 00:00:00
freq                     1941
first     2014-10-28 00:00:00
last      2015-03-04 00:00:00
Name: date, dtype: object

In [5]:
# calculate summary statistics for the “shot_clock” variable.
Shotlog_1415['shot_clock'].describe()

count    122502.000000
mean         12.453344
std           5.763265
min           0.000000
25%           8.200000
50%          12.300000
75%          16.675000
max          24.000000
Name: shot_clock, dtype: float64

In [6]:
Shotlog_1415.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128069 entries, 0 to 128068
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   game_id               128069 non-null  int64
 1   date                  128069 non-null  datetime64[ns]
 2   match                 128069 non-null  object
 3   home_team             128069 non-null  object
 4   away_team             128069 non-null  object
 5   home_away             128069 non-null  object
 6   result                128069 non-null  object
 7   final_margin          128069 non-null  int64
 8   shot_number           128069 non-null  int64
 9   quarter               128069 non-null  int64
 10  game_clock            128069 non-null  object
 11  shot_clock            122502 non-null  float64
 12  dribbles              128069 non-null  int64
 13  touch_time            128069 non-null  float64
 14  shot_dist             128069 non-null  float64
 15  points                128069 non-null  int64
 16  current_shot_outcome  128069 non-null  object
 17  closest_defender      128069 non-null  object
 18  closest_defender_id   128069 non-null  int64
 19  closest_def_dist      128069 non-null  float64
 20  current_shot_hit      128069 non-null  int64
 21  points_earned         128069 non-null  int64
 22  shoot_player          128069 non-null  object
 23  player_id             128069 non-null  int64
 24  average_hit           128069 non-null  float64
 25  shot_count            128069 non-null  int64
 26  shot_per_game         128069 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(12), object(9)
memory usage: 26.4+ MB

In [7]:
#Create a lagged variable “lag_shot_hit” to indicate the result of the previous shot by the same player at the same game.
Shotlog_1415['lag_shot_hit']=Shotlog_1415.sort_values(by=['player_id', 'game_id', 'shot_number'], ascending=[True, True, True]).groupby(['player_id', 'game_id'])['current_shot_hit'].shift(1)
Shotlog_1415.head()

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,...,closest_defender_id,closest_def_dist,current_shot_hit,points_earned,shoot_player,player_id,average_hit,shot_count,shot_per_game,lag_shot_hit
0,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,1,1,...,201572,6.6,1,2,al horford,201143,0.541259,715,10,NaN
1,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,2,1,...,201572,5.6,0,0,al horford,201143,0.541259,715,10,1.0
2,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,3,1,...,201572,4.7,0,0,al horford,201143,0.541259,715,10,0.0
3,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,4,1,...,201572,5.8,0,0,al horford,201143,0.541259,715,10,0.0
4,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,5,2,...,201572,6.4,0,0,al horford,201143,0.541259,715,10,0.0

In [8]:
#Create a variable “error” to indicate the prediction error for each shot and a variable “lagerror” for the 
# prediction error for the previous shot. The “error” variable is defined as the difference between the outcome of the 
# current shot and the average success rate (“average_hit”) and the “lagerror” variable is defined as the difference 
# between the outcome of the previous shot and the average success rate.

Shotlog_1415['error']=Shotlog_1415['current_shot_hit']-Shotlog_1415['average_hit']
Shotlog_1415['lagerror']=Shotlog_1415['lag_shot_hit']-Shotlog_1415['average_hit']

In [9]:
# Calculate summary statistics for the “error” and “lagerror” variables. 
Shotlog_1415['error'].describe()

count    1.280690e+05
mean    -5.770049e-18
std      4.949640e-01
min     -7.124682e-01
25%     -4.491979e-01
50%     -3.850837e-01
75%      5.395973e-01
max      6.914894e-01
Name: error, dtype: float64

In [10]:
Shotlog_1415['lagerror'].describe()

count    113726.000000
mean          0.006303
std           0.496035
min          -0.712468
25%          -0.449198
50%          -0.382143
75%           0.542254
max           0.691489
Name: lagerror, dtype: float64

In [11]:
Player_Stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   shoot_player  281 non-null    object
 1   average_hit   281 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB

## Part 2 - Conditional Probability and Autocorrelation

In [12]:
# Create a dummy variable “conse_shot” that indicates a player made consecutive shots. 
Shotlog_1415['conse_shot_hit'] = np.where((Shotlog_1415['current_shot_hit']==1)&(Shotlog_1415['lag_shot_hit']==1), 1, 0)
Shotlog_1415.head()

,game_id,date,match,home_team,away_team,home_away,result,final_margin,shot_number,quarter,...,points_earned,shoot_player,player_id,average_hit,shot_count,shot_per_game,lag_shot_hit,error,lagerror,conse_shot_hit
0,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,1,1,...,2,al horford,201143,0.541259,715,10,NaN,0.458741,NaN,0
1,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,2,1,...,0,al horford,201143,0.541259,715,10,1.0,-0.541259,0.458741,0
2,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,3,1,...,0,al horford,201143,0.541259,715,10,0.0,-0.541259,-0.541259,0
3,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,4,1,...,0,al horford,201143,0.541259,715,10,0.0,-0.541259,-0.541259,0
4,21400280,2014-12-05,ATL @ BKN,BKN,ATL,A,W,23,5,2,...,0,al horford,201143,0.541259,715,10,0.0,-0.541259,-0.541259,0

In [13]:
Shotlog_1415 = Shotlog_1415.rename(columns={'conse_shot_hit': 'conse_shot'})

In [14]:
#Create a dataframe “Player_Prob” for the probability of making the previous shot and the joint probability for
# making both the previous and current shots. Name the probability of making the previous shot “average_lag_hit” and 
# the probability of making both shots “conse_shot_hit.” 

Player_Prob = Shotlog_1415.groupby(['shoot_player'])['conse_shot','lag_shot_hit'].mean()
Player_Prob=Player_Prob.reset_index()
Player_Prob.rename(columns={'lag_shot_hit':'average_lag_hit'}, inplace=True)
Player_Prob['conse_shot_hit']=Player_Prob['conse_shot']/Player_Prob['average_lag_hit']
Player_Prob.head()

      shoot_player  conse_shot  average_lag_hit  conse_shot_hit
0     aaron brooks    0.153298         0.418000        0.366741
1     aaron gordon    0.201923         0.532468        0.379221
2  al farouq aminu    0.162791         0.465686        0.349572
3       al horford    0.262937         0.537994        0.488736
4     al jefferson    0.207500         0.480000        0.432292

In [15]:
Player_Prob.rename(columns={'conse_shot':'conse_shot_hit','conse_shot_hit':'conditional_prob'}, inplace=True)

In [16]:
Player_Prob.head()

      shoot_player  conse_shot_hit  average_lag_hit  conditional_prob
0     aaron brooks        0.153298         0.418000          0.366741
1     aaron gordon        0.201923         0.532468          0.379221
2  al farouq aminu        0.162791         0.465686          0.349572
3       al horford        0.262937         0.537994          0.488736
4     al jefferson        0.207500         0.480000          0.432292

In [17]:
# Merge the “Player_Prob” dataframe into the “Player_Stats” dataframe.
Player_Stats=pd.merge(Player_Prob, Player_Stats, on=['shoot_player'])
Player_Stats.head(10)

,shoot_player,conse_shot_hit,average_lag_hit,conditional_prob,average_hit
0,aaron brooks,0.153298,0.418000,0.366741,0.415330
1,aaron gordon,0.201923,0.532468,0.379221,0.528846
2,al farouq aminu,0.162791,0.465686,0.349572,0.430233
3,al horford,0.262937,0.537994,0.488736,0.541259
4,al jefferson,0.207500,0.480000,0.432292,0.477500
5,alan anderson,0.157270,0.462366,0.340142,0.433234
6,alan crabbe,0.138298,0.523810,0.264023,0.425532
7,alex len,0.247492,0.539419,0.458811,0.528428
8,alexis ajinca,0.284360,0.598802,0.474882,0.597156
9,alonzo gee,0.137681,0.460784,0.298797,0.478261

In [18]:
Player_Stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 281 entries, 0 to 280
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   shoot_player      281 non-null    object
 1   conse_shot_hit    281 non-null    float64
 2   average_lag_hit   281 non-null    float64
 3   conditional_prob  281 non-null    float64
 4   average_hit       281 non-null    float64
dtypes: float64(4), object(1)
memory usage: 13.2+ KB

In [19]:
# Calculate summary statistics for the probability for a player to make a shot (“average_hit”) and the 
# conditional probability for a player to make a shot given that he made the previous one (“conditional_prob”) and 
# the probability of players making consecutive shots (“conse_shot_hit”).

Player_Stats['average_hit'].describe()

count    281.000000
mean       0.451545
std        0.059392
min        0.308511
25%        0.413223
50%        0.446078
75%        0.480480
max        0.712468
Name: average_hit, dtype: float64

In [20]:
Player_Stats['conditional_prob'].describe()

count    281.000000
mean       0.380233
std        0.062320
min        0.225801
25%        0.336689
50%        0.381570
75%        0.422801
max        0.613209
Name: conditional_prob, dtype: float64

In [21]:
Player_Stats['conse_shot_hit'].describe()

count    281.000000
mean       0.176987
std        0.047943
min        0.076190
25%        0.144543
50%        0.171625
75%        0.203512
max        0.422392
Name: conse_shot_hit, dtype: float64

In [22]:
#Perform a t-test for the statistical significance on the difference between conditional probability 
#and unconditional probability of making a shot.

sp.stats.ttest_ind(Player_Stats['conditional_prob'], Player_Stats['average_hit'])

Ttest_indResult(statistic=-13.885932802814914, pvalue=6.925846314604593e-38)

In [23]:
#Calculate the first order autocorrelation coefficient on making a shot 
#(correlation coefficient between making the current shot and the previous shot) for the entire shotlog dataset.
Shotlog_1415['current_shot_hit'].corr(Shotlog_1415['lag_shot_hit'])

-0.010502388301693177

In [24]:
#Calculate the first order autocorrelation coefficient on making a shot for each player. 
#Display the top ten players with the highest first order autocorrelation coefficient.

Shotlog_1415.groupby('shoot_player')[['current_shot_hit','lag_shot_hit']].corr().head(10)

                                  current_shot_hit  lag_shot_hit
shoot_player
aaron brooks    current_shot_hit          1.000000      0.002556
                lag_shot_hit              0.002556      1.000000
aaron gordon    current_shot_hit          1.000000     -0.071283
                lag_shot_hit             -0.071283      1.000000
al farouq aminu current_shot_hit          1.000000      0.029513
                lag_shot_hit              0.029513      1.000000
al horford      current_shot_hit          1.000000     -0.008396
                lag_shot_hit             -0.008396      1.000000
al jefferson    current_shot_hit          1.000000     -0.038885
                lag_shot_hit             -0.038885      1.000000

In [25]:
Autocorr_Hit=Shotlog_1415.groupby('shoot_player')[['current_shot_hit','lag_shot_hit']].corr().unstack().iloc[:,1].reset_index()
Autocorr_Hit.columns=Autocorr_Hit.columns.get_level_values(0)
Autocorr_Hit.rename(columns={'current_shot_hit':'autocorr'}, inplace=True)
Autocorr_Hit.head(10)

      shoot_player  autocorr
0     aaron brooks  0.002556
1     aaron gordon -0.071283
2  al farouq aminu  0.029513
3       al horford -0.008396
4     al jefferson -0.038885
5    alan anderson -0.022688
6      alan crabbe  0.028048
7         alex len  0.118461
8    alexis ajinca  0.047444
9       alonzo gee -0.250290

In [26]:
Autocorr_Hit= Autocorr_Hit.sort_values(by='autocorr', ascending=False)
Autocorr_Hit.head(10)

         shoot_player  autocorr
131       joey dorsey  0.334252
54       cole aldrich  0.174666
200     nate robinson  0.122107
267  tyler hansbrough  0.120608
7            alex len  0.118461
50        cj mccollum  0.115949
114       jason smith  0.105903
190       matt bonner  0.098577
143      jusuf nurkic  0.097465
195       mike miller  0.089366

## Part 3 - Regression Analyses

In [27]:
# In this section, you will run several regressions to investigate the “hot hand.” 
#In all the regressions, the dependent variable is “error” and the independent variable of interest is “lagerror.”

In [28]:
# Reg1: Run a linear least squares regression using the entire shotlog dataframe. Include the following control variables:

#Shot distance

#Number of dribbles

#Touch time

#Type of shot (“points” variable)

#Quarter of the game (as a categorical variable)

#Home or away game

#Shoot_player

#Closest defender

#Closest defender distance

In [29]:
Shotlog_1415.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128069 entries, 0 to 128068
Data columns (total 31 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   game_id               128069 non-null  int64
 1   date                  128069 non-null  datetime64[ns]
 2   match                 128069 non-null  object
 3   home_team             128069 non-null  object
 4   away_team             128069 non-null  object
 5   home_away             128069 non-null  object
 6   result                128069 non-null  object
 7   final_margin          128069 non-null  int64
 8   shot_number           128069 non-null  int64
 9   quarter               128069 non-null  int64
 10  game_clock            128069 non-null  object
 11  shot_clock            122502 non-null  float64
 12  dribbles              128069 non-null  int64
 13  touch_time            128069 non-null  float64
 14  shot_dist             128069 non-null  float64
 15  points                128069 non-null  int64
 16  current_shot_outcome  128069 non-null  object
 17  closest_defender      128069 non-null  object
 18  closest_defender_id   128069 non-null  int64
 19  closest_def_dist      128069 non-null  float64
 20  current_shot_hit      128069 non-null  int64
 21  points_earned         128069 non-null  int64
 22  shoot_player          128069 non-null  object
 23  player_id             128069 non-null  int64
 24  average_hit           128069 non-null  float64
 25  shot_count            128069 non-null  int64
 26  shot_per_game         128069 non-null  int64
 27  lag_shot_hit          113726 non-null  float64
 28  error                 128069 non-null  float64
 29  lagerror              113726 non-null  float64
 30  conse_shot            128069 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(13), object(9)
memory usage: 30.3+ MB

In [30]:
#Shotlog_1415['shoot_player'] = Shotlog_1415['shoot_player'].astype('category')
#Shotlog_1415['closest_defender'] = Shotlog_1415['closest_defender'].astype('category')

In [31]:
Shotlog_1415['error_demeaned'] = Shotlog_1415['error'] - Shotlog_1415.groupby('player_id')['error'].transform('mean')
Shotlog_1415['lagerror_demeaned'] = Shotlog_1415['lagerror'] - Shotlog_1415.groupby('player_id')['lagerror'].transform('mean')

In [32]:
Reg1 = sm.ols(formula = 'error_demeaned ~ lagerror_demeaned + shot_dist + dribbles + touch_time + C(points) + C(quarter) + home_away + closest_def_dist', data= Shotlog_1415).fit()
print(Reg1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         error_demeaned   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.041
Method:                 Least Squares   F-statistic:                     376.4
Date:                Mon, 13 Apr 2026   Prob (F-statistic):               0.00
Time:                        23:51:53   Log-Likelihood:                -79034.
No. Observations:              113726   AIC:                         1.581e+05
Df Residuals:                  113712   BIC:                         1.582e+05
Df Model:                          13
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.1113      0.005     23.279      0.000       0.102       0.121
C(points)[T.3]        0.0495      0.005      9.978      0.000       0.040       0.059
C(quarter)[T.2]      -0.0056      0.004     -1.314      0.189      -0.014       0.003
C(quarter)[T.3]      -0.0016      0.004     -0.386      0.700      -0.010       0.007
C(quarter)[T.4]      -0.0049      0.004     -1.123      0.261      -0.013       0.004
C(quarter)[T.5]      -0.0420      0.016     -2.561      0.010      -0.074      -0.010
C(quarter)[T.6]       0.0116      0.038      0.309      0.757      -0.062       0.085
C(quarter)[T.7]      -0.0431      0.074     -0.582      0.561      -0.188       0.102
home_away[T.H]        0.0065      0.003      2.276      0.023       0.001       0.012
lagerror_demeaned    -0.0067      0.003     -2.312      0.021      -0.012      -0.001
shot_dist            -0.0145      0.000    -55.650      0.000      -0.015      -0.014
dribbles              0.0086      0.001      8.575      0.000       0.007       0.011
touch_time           -0.0132      0.001    -11.485      0.000      -0.015      -0.011
closest_def_dist      0.0225      0.001     36.578      0.000       0.021       0.024
==============================================================================
Omnibus:                   478367.329   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14685.145
Skew:                           0.184   Prob(JB):                         0.00
Kurtosis:                       1.279   Cond. No.                         876.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [33]:
Reg2 = sm.wls(formula = 'error_demeaned ~ lagerror_demeaned + shot_dist + dribbles + touch_time + C(points) + C(quarter) + home_away + closest_def_dist',  weights=1/Shotlog_1415['shot_per_game'] , data= Shotlog_1415).fit()
print(Reg2.summary())

                            WLS Regression Results
==============================================================================
Dep. Variable:         error_demeaned   R-squared:                       0.042
Model:                            WLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     380.7
Date:                Mon, 13 Apr 2026   Prob (F-statistic):               0.00
Time:                        23:51:58   Log-Likelihood:                -88157.
No. Observations:              113726   AIC:                         1.763e+05
Df Residuals:                  113712   BIC:                         1.765e+05
Df Model:                          13
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.0975      0.005     20.249      0.000       0.088       0.107
C(points)[T.3]        0.0590      0.005     11.876      0.000       0.049       0.069
C(quarter)[T.2]   -6.631e-05      0.004     -0.015      0.988      -0.009       0.008
C(quarter)[T.3]       0.0041      0.004      0.948      0.343      -0.004       0.013
C(quarter)[T.4]       0.0071      0.004      1.627      0.104      -0.001       0.016
C(quarter)[T.5]      -0.0112      0.019     -0.580      0.562      -0.049       0.027
C(quarter)[T.6]       0.0409      0.045      0.912      0.362      -0.047       0.129
C(quarter)[T.7]      -0.0866      0.087     -0.991      0.322      -0.258       0.085
home_away[T.H]        0.0059      0.003      2.063      0.039       0.000       0.012
lagerror_demeaned    -0.0023      0.003     -0.793      0.428      -0.008       0.003
shot_dist            -0.0150      0.000    -57.327      0.000      -0.015      -0.014
dribbles              0.0074      0.001      7.401      0.000       0.005       0.009
touch_time           -0.0116      0.001    -10.332      0.000      -0.014      -0.009
closest_def_dist      0.0225      0.001     36.877      0.000       0.021       0.024
==============================================================================
Omnibus:                    53334.783   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6514.875
Skew:                           0.178   Prob(JB):                         0.00
Kurtosis:                       1.883   Cond. No.                     1.04e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [34]:
#Reg3_player: Run linear least squares regressions on individual players. Include the following control variables:

#Shot distance

#Number of dribbles

#Touch time

#Type of shot (“points” variable)

#Quarter of the game (as a categorical variable)

#Home or away game

#Closest defender distance

# Reg4_wls_player: Run weighted least squares regressions on individual players. 
#Include the same set of control variables as in Reg3. 
#The regression should be weighted by the number of shot per game (weight=1/shot_per_game).

In [35]:
def Reg3_player(player):
    Shotlog_1415_player=Shotlog_1415[Shotlog_1415.shoot_player==player]
    Reg3_player=sm.ols(formula = 'error ~ lagerror + shot_dist + dribbles + touch_time + C(points) + C(quarter) + home_away + closest_def_dist', data= Shotlog_1415_player).fit()
    #print(Reg3_player.summary())
    return Reg3_player;

In [36]:
def Reg4_wls_player(player):
    Shotlog_1415_player=Shotlog_1415[Shotlog_1415.shoot_player==player]
    Reg4_wls_player=sm.wls(formula = 'error ~ lagerror + shot_dist + dribbles + touch_time + C(points) + C(quarter) + home_away + closest_def_dist', weights=1/Shotlog_1415_player['shot_per_game'] , data= Shotlog_1415_player).fit()
    #print(Reg4_wls_player.summary())
    return Reg4_wls_player;

In [37]:
player_list = np.array(Shotlog_1415['shoot_player'])
player_list = np.unique(player_list)

In [38]:
i = 0 
Player_Results_OLS = {}
while i <= len(player_list) - 1:
    #Shotlog_player=Shotlog[Shotlog.shoot_player==player_list[i]]
    reg_player = Reg3_player(player_list[i])
    RegParams = pd.DataFrame(reg_player.params).reset_index()
    RegTvals = pd.DataFrame(reg_player.tvalues).reset_index()
    RegPvals = pd.DataFrame(reg_player.pvalues).reset_index()

    RegOutput = pd.merge(RegParams, RegTvals, on=['index'])
    RegOutput = pd.merge(RegOutput, RegPvals, on=['index'])
    RegOutput
    
    LagErr = RegOutput[RegOutput['index'] == 'lagerror']
    LagErr = LagErr.drop(columns=['index'])
    LagErr = LagErr.rename(columns={"0_x":"Coef", "0_y":"T_Statistics", 0:"P_Value"})
    LagErr['shoot_player'] = player_list[i]
    Headers = ['shoot_player', 'Coef', 'T_Statistics', 'P_Value']
    Player_Results_OLS[i] = LagErr[Headers]
    i = i+1

In [39]:
RegPlayer_OLS = Player_Results_OLS[0]
j = 1
while j <= len(player_list) - 1:
    RegPlayer_OLS = RegPlayer_OLS.append(Player_Results_OLS[j])
    j = j+1
RegPlayer_OLS = RegPlayer_OLS.reset_index()
RegPlayer_OLS = RegPlayer_OLS.drop(columns=['index'])
RegPlayer_OLS

        shoot_player      Coef  T_Statistics   P_Value
0       aaron brooks -0.004151     -0.093202  0.925781
1       aaron gordon -0.079465     -0.656347  0.513918
2    al farouq aminu  0.096741      1.513574  0.131770
3         al horford -0.002522     -0.067241  0.946411
4       al jefferson -0.023667     -0.654268  0.513143
..               ...       ...           ...       ...
276  wesley matthews -0.047961     -1.249311  0.211984
277  wilson chandler -0.052219     -1.395720  0.163266
278      zach lavine -0.016481     -0.298785  0.765306
279    zach randolph  0.049032      1.207406  0.227746
280    zaza pachulia -0.021562     -0.373902  0.708754

[281 rows x 4 columns]

In [40]:
i = 0 
Player_Results_WLS = {}
while i <= len(player_list) - 1:
    #Shotlog_player=Shotlog[Shotlog.shoot_player==player_list[i]]
    reg_player = Reg4_wls_player(player_list[i])
    RegParams = pd.DataFrame(reg_player.params).reset_index()
    RegTvals = pd.DataFrame(reg_player.tvalues).reset_index()
    RegPvals = pd.DataFrame(reg_player.pvalues).reset_index()

    RegOutput = pd.merge(RegParams, RegTvals, on=['index'])
    RegOutput = pd.merge(RegOutput, RegPvals, on=['index'])
    RegOutput
    
    LagErr = RegOutput[RegOutput['index'] == 'lagerror']
    LagErr = LagErr.drop(columns=['index'])
    LagErr = LagErr.rename(columns={"0_x":"Coef", "0_y":"T_Statistics", 0:"P_Value"})
    LagErr['shoot_player'] = player_list[i]
    Headers = ['shoot_player', 'Coef', 'T_Statistics', 'P_Value']
    Player_Results_WLS[i] = LagErr[Headers]
    i = i+1

In [41]:
RegPlayer_WLS = Player_Results_WLS[0]
j = 1
while j <= len(player_list) - 1:
    RegPlayer_WLS = RegPlayer_WLS.append(Player_Results_WLS[j])
    j = j+1
RegPlayer_WLS = RegPlayer_WLS.reset_index()
RegPlayer_WLS = RegPlayer_WLS.drop(columns=['index'])
RegPlayer_WLS

        shoot_player      Coef  T_Statistics   P_Value
0       aaron brooks -0.017039     -0.379413  0.704547
1       aaron gordon -0.086933     -0.723936  0.471703
2    al farouq aminu  0.107612      1.706157  0.089587
3         al horford  0.005338      0.142661  0.886602
4       al jefferson -0.042479     -1.176217  0.239888
..               ...       ...           ...       ...
276  wesley matthews -0.024813     -0.643336  0.520225
277  wilson chandler -0.039111     -1.054474  0.292050
278      zach lavine -0.055391     -1.018136  0.309415
279    zach randolph  0.050400      1.246013  0.213240
280    zaza pachulia  0.002462      0.042237  0.966339

[281 rows x 4 columns]

In [44]:
pd.set_option('display.max_rows', 300)
display(RegPlayer_OLS)

                 shoot_player      Coef  T_Statistics   P_Value
0                aaron brooks -0.004151     -0.093202  0.925781
1                aaron gordon -0.079465     -0.656347  0.513918
2             al farouq aminu  0.096741      1.513574  0.131770
3                  al horford -0.002522     -0.067241  0.946411
4                al jefferson -0.023667     -0.654268  0.513143
5               alan anderson  0.007989      0.134741  0.892918
6                 alan crabbe  0.071764      0.607910  0.545893
7                    alex len  0.106514      1.736104  0.083885
8               alexis ajinca  0.011545      0.150916  0.880236
9                  alonzo gee -0.273124     -2.778511  0.006647
10           amare stoudemire -0.047338     -0.836439  0.403609
11               amir johnson -0.060925     -1.139448  0.255338
12             andre drummond  0.067927      1.708620  0.088045
13             andre iguodala  0.025597      0.453961  0.650215
14               andre miller  0.050424      0.547462  0.585150
15             andre roberson -0.035392     -0.412314  0.680898
16               andrew bogut -0.008576     -0.124659  0.900929
17             andrew wiggins -0.001568     -0.043663  0.965185
18            anthony bennett -0.093265     -1.394920  0.164486
19              anthony davis  0.017951      0.526654  0.598583
20             anthony morrow -0.023258     -0.450237  0.652820
21                aron baynes -0.137415     -1.952514  0.052309
22              arron afflalo -0.010741     -0.270138  0.787145
23              avery bradley  0.054532      1.471703  0.141560
24                 ben gordon -0.001111     -0.015598  0.987571
25               ben mclemore  0.053230      1.247158  0.212912
26                 beno urdih  0.007156      0.128447  0.897885
27            bismack biyombo -0.103051     -0.947884  0.346404
28              blake griffin  0.009085      0.269641  0.787504
29           bojan bogdanovic  0.052375      0.951964  0.341903
30                 boris diaw -0.020926     -0.406503  0.684612
31               bradley beal -0.095855     -2.237739  0.025655
32               brandon bass  0.005059      0.103805  0.917375
33           brandon jennings  0.006398      0.142203  0.886978
34             brandon knight -0.042197     -1.178108  0.239124
35              brian roberts  0.066050      1.142087  0.254326
36                brook lopez  0.004399      0.106270  0.915406
37                carl landry  0.015553      0.236198  0.813493
38              carlos boozer -0.043910     -1.052127  0.293203
39            carmelo anthony -0.047051     -1.298464  0.194532
40               caron butler -0.057688     -0.854537  0.393729
41           chandler parsons  0.002648      0.066422  0.947064
42              channing frye  0.003968      0.073310  0.941603
43         charlie villanueva  0.018466      0.242235  0.808862
44             chase budinger  0.088332      1.036385  0.301760
45             chris andersen -0.087412     -0.912249  0.364159
46                 chris bosh -0.025015     -0.663070  0.507507
47             chris copeland -0.109200     -1.814257  0.070823
48                chris kaman -0.048265     -0.951304  0.342074
49                 chris paul  0.025538      0.733034  0.463750
50                cj mccollum  0.115454      1.264184  0.208516
51                   cj miles  0.001204      0.027244  0.978276
52                  cj watson  0.022851      0.366747  0.714121
53                cody zeller -0.038063     -0.664367  0.506994
54               cole aldrich  0.143681      1.817654  0.071210
55                cory joseph  0.034083      0.587953  0.557045
56               courtney lee  0.030905      0.634421  0.526164
57             damian lillard  0.033869      1.047880  0.294971
58               damjan rudez -0.046024     -0.547061  0.585247
59            danilo gallinai -0.007592     -0.134171  0.893358
60                danny green  0.003353      0.075190  0.940095
61           dante cunningham -0.024137     -0.339247  0.734797
62                 dante exum  0.011349      0.182832  0.855103
63             darrell arthur -0.033709     -0.600021  0.548966
64            darren collison -0.008139     -0.184038  0.854059
65                 david west -0.046656     -1.017315  0.309543
66             deandre jordan  0.014356      0.281598  0.778434
67           demarcus cousins  0.009582      0.265939  0.790361
68            demarre carroll -0.049624     -1.016792  0.309869
69            dennis schroder -0.043053     -0.858073  0.391386
70             deron williams  0.027506      0.592948  0.553510
71             derrick favors -0.007354     -0.188033  0.850914
72               derrick rose  0.041869      1.133641  0.257325
73           derrick williams -0.047356     -0.752906  0.452283
74               devin harris  0.018359      0.360396  0.718763
75             dirk nowtizski -0.031198     -0.856049  0.392246
76                dj augustin -0.025751     -0.559179  0.576316
77               donald sloan  0.103398      1.852182  0.065030
78         donatas motiejunas -0.036447     -0.839641  0.401507
79             draymond green  0.036624      0.825342  0.409586
80                dwayne wade  0.031136      0.820523  0.412219
81              dwight howard -0.034325     -0.627489  0.530829
82                   ed davis  0.003712      0.065608  0.947736
83              elfrid payton  0.059604      1.222962  0.222054
84                enes kanter -0.054201     -1.367930  0.171871
85               eric bledsoe -0.006982     -0.191386  0.848279
86              evan fournier -0.100684     -2.300302  0.021851
87                evan turner -0.015365     -0.321284  0.748152
88             garrett temple  0.015182      0.163100  0.870731
89                  gary neal -0.042923     -0.874456  0.382398
90               gerald green -0.030030     -0.727920  0.466967
91           gerald henderson  0.037899      0.865275  0.387309
92      giannis antetokounmpo -0.020718     -0.476021  0.634278
93                 glen davis -0.061299     -0.713636  0.476873
94               goran dragic -0.061030     -1.719654  0.085950
95             gordon hayward -0.026913     -0.774001  0.439160
96               gorgui dieng -0.084570     -1.590111  0.112747
97                greg monroe -0.005779     -0.151343  0.879752
98                 greg smith -0.028833     -0.081064  0.936990
99            greivis vasquez -0.042314     -0.935388  0.350069
100           harrison barnes  0.007848      0.160843  0.872299
101             hedo turkoglu  0.005324      0.043864  0.965166
102                henry sims  0.019746      0.379183  0.704781
103           hollis thompson -0.003565     -0.061161  0.951274
104             isaiah thomas  0.030904      0.727459  0.467253
105            jakarr sampson -0.004005     -0.051371  0.959097
106            jamal crawford -0.008060     -0.219655  0.826201
107               james ennis -0.045008     -0.469289  0.639827
108              james harden  0.025725      0.821210  0.411726
109             james johnson -0.010445     -0.180120  0.857204
110              jared dudley -0.038964     -0.674174  0.500739
111           jared sullinger -0.052273     -1.324566  0.185818
112              jarrett jack -0.014997     -0.364792  0.715409
113             jason maxiell  0.030316      0.278141  0.781613
114               jason smith  0.104200      2.027022  0.043397
115               jason terry -0.031769     -0.519503  0.603836
116            jason thompson  0.023291      0.359293  0.719717
117                jeff green  0.019924      0.523036  0.601129
118               jeff teague  0.035848      0.920145  0.357855
119              jerami grant  0.082623      1.073598  0.284600
120               jeremy lamb  0.121065      1.572502  0.117640
121                jeremy lin  0.076568      1.667952  0.096030
122             jerome jordan -0.023226     -0.164568  0.869961
123            jerryd bayless  0.020912      0.389082  0.697463
124           jimmer dredette -0.049790     -0.541170  0.589570
125              jimmy butler -0.047406     -1.312498  0.189774
126                jj hickson -0.025407     -0.460652  0.645418
127                 jj redick -0.019016     -0.463080  0.643481
128               joakim noah -0.062694     -1.066088  0.287312
129                joe harris -0.067277     -0.500327  0.618841
130               joe johnson -0.012325     -0.328016  0.742998
131               joey dorsey  0.351285      2.512531  0.015727
132               john henson -0.068362     -0.967262  0.334669
133                 john wall  0.007895      0.229223  0.818755
134                jon ingles -0.066650     -0.889942  0.374876
135                 jon leuer  0.077880      1.199585  0.231756
136             jonas jerebko -0.003302     -0.043199  0.965593
137         jonas valanciunas  0.046387      0.976078  0.329594
138             jordan farmar -0.042411     -0.436895  0.663036
139               jordan hill  0.012400      0.298416  0.765500
140             jose calderon  0.025946      0.454179  0.650036
141           jose juan barea -0.061261     -1.188178  0.235567
142              jrue holiday  0.036587      0.789822  0.430039
143              jusuf nurkic  0.105091      1.631087  0.104195
144             kawhi leonard  0.068654      1.505311  0.132927
145              kelly olynyk -0.007228     -0.124790  0.900777
146              kemba walker -0.024255     -0.627272  0.530705
147          kendrick perkins -0.046414     -0.549888  0.583325
148            kenneth faried  0.077154      1.692882  0.091178
149             kent bazemore -0.052020     -0.684572  0.494699
150  kentavious caldwell-pope -0.012167     -0.303777  0.761402
151             kevin garnett -0.106920     -1.689254  0.092448
152                kevin love -0.057597     -1.546827  0.122357
153            kevin seraphin -0.029248     -0.492012  0.623114
154           khris middleton  0.018004      0.412575  0.680098
155              kirk hinrich -0.120217     -1.927822  0.054992
156              kj mcdaniels -0.068545     -1.316915  0.188726
157             klay thompson -0.000152     -0.004591  0.996338
158               kobe bryant -0.020605     -0.538106  0.590684
159              kosta koufos -0.069100     -0.967832  0.334378
160       kostas papanikolaou  0.075362      0.960440  0.338526
161            kris humphries  0.000922      0.017037  0.986417
162               kyle korver  0.003574      0.072975  0.941862
163                kyle lowry -0.026185     -0.763605  0.445325
164               kyle oquinn -0.079379     -1.040590  0.299656
165              kyle singler -0.108743     -1.956720  0.051278
166              kyrie irving -0.043618     -1.288895  0.197776
167         lamarcus aldridge -0.000697     -0.022178  0.982310
168          lance stephenson -0.084194     -1.729847  0.084474
169               lavoy allen  0.009778      0.152191  0.879190
170           leandro barbosa -0.052708     -0.791506  0.429587
171              lebron james -0.030923     -0.980227  0.327233
172              lou williams  0.003528      0.089626  0.928614
173          luc mbah a moute -0.040904     -0.884114  0.377133
174                luis scola -0.019094     -0.394202  0.693642
175              luke babbitt -0.000491     -0.005090  0.995949
176                 luol deng -0.069252     -1.592386  0.111927
177             manu ginobili -0.004087     -0.087426  0.930374
178                marc gasol -0.087448     -2.429448  0.015358
179             marcin gortat -0.008041     -0.191646  0.848098
180           marco belinelli -0.028193     -0.462884  0.643820
181             marcus morris  0.047805      1.045219  0.296468
182              marcus smart  0.077627      1.267915  0.206042
183           marcus thornton -0.089559     -1.467988  0.143307
184            mario chalmers  0.030662      0.658920  0.510287
185           markieff morris  0.026140      0.729909  0.465672
186         marreese speights  0.040967      0.838978  0.401945
187           marvin williams -0.090503     -1.471209  0.142487
188             mason plumlee  0.070850      1.357054  0.175686
189               matt barnes -0.028355     -0.561181  0.575005
190               matt bonner  0.114825      1.384954  0.168254
191       matthew dellavedova -0.081510     -1.012792  0.312769
192   michael carter-williams  0.022892      0.581381  0.561202
193    michael kidd-gilchrist -0.109766     -1.994229  0.046986
194               mike conley -0.050140     -1.293428  0.196318
195               mike miller  0.068220      0.482991  0.631169
196                mike scott  0.007813      0.139807  0.888907
197           mirza teletovic  0.014302      0.239466  0.810928
198                mnta ellis  0.017256      0.547377  0.584245
199               mo williams -0.078472     -1.782167  0.075327
200             nate robinson  0.147884      1.819494  0.070729
201              nene hilario -0.007561     -0.162255  0.871184
202               nerles noel -0.006505     -0.131329  0.895585
203             nick collison -0.061454     -0.810781  0.418776
204                nick young -0.090566     -1.902837  0.057747
205             nicolas batum  0.024832      0.502657  0.615492
206              nik stauskas  0.006603      0.080003  0.936355
207            nikola mirotic -0.037858     -0.670841  0.502850
208            nikola vucevic -0.002242     -0.066276  0.947174
209               norris cole -0.014067     -0.251605  0.801518
210                   oj mayo -0.029438     -0.683232  0.494776
211                 omer asik -0.091887     -1.463430  0.144697
212               omri casspi -0.013694     -0.198847  0.842601
213               otto porter -0.006022     -0.091175  0.927437
214            pablo prigioni -0.120466     -1.341485  0.182339
215          patrick beverley -0.097964     -2.026932  0.043337
216         patrick patterson -0.027678     -0.505846  0.613298
217                 pau gasol -0.018062     -0.496754  0.619509
218              paul millsap -0.035609     -0.976507  0.329159
219               paul pierce -0.033777     -0.726062  0.468171
220                pero antic  0.010571      0.140272  0.888616
221                 pj tucker -0.032238     -0.607180  0.544140
222                quincy acy -0.067982     -0.910673  0.363713
223            ramon sessions  0.030178      0.393587  0.694394
224             rasual butler -0.081890     -1.558614  0.120013
225              ray mccallum  0.090587      1.243772  0.215132
226            reggie jackson  0.088591      2.232071  0.025984
227         richard jefferson -0.100145     -1.379175  0.169591
228             robbie hummel -0.074335     -0.659831  0.511306
229          robert covington  0.035476      0.769593  0.441945
230              robert sacre -0.058013     -0.814729  0.416304
231            rodney stuckey -0.056530     -1.259523  0.208463
232              ronnie price  0.099832      1.333979  0.184006
233               roy hibbert -0.118469     -2.565794  0.010609
234                  rudy gay  0.009614      0.280682  0.779026
235               rudy gobert  0.039650      0.591831  0.554639
236         russell westbrook -0.009032     -0.275313  0.783139
237             ryan anderson  0.006607      0.160240  0.872747
238               serge ibaka -0.000904     -0.023871  0.980963
239          shabazz muhammad -0.065276     -1.261716  0.207906
240            shabazz napier -0.035537     -0.445084  0.656888
241              shane larkin -0.160471     -2.443467  0.015361
242          shaun livingston  0.053988      0.780368  0.436111
243              shawn marion -0.011744     -0.163825  0.870061
244           shawne williams -0.061470     -0.850299  0.396270
245              solomon hill -0.101741     -2.117115  0.034856
246             spencer hawes -0.072961     -1.194635  0.233282
247             stephen curry -0.060747     -1.861740  0.062966
248               steve adams  0.019553      0.296818  0.766896
249               steve blake  0.010428      0.140619  0.888333
250                taj gibson -0.014356     -0.279128  0.780308
251             terrence ross -0.006968     -0.155623  0.876394
252           thabo sefolosha  0.071454      0.899643  0.369772
253            thaddeus young -0.002997     -0.077839  0.937981
254                tim duncan  0.018731      0.454050  0.649969
255          time hardaway jr -0.019101     -0.442124  0.658582
256            timofey mozgov  0.036474      0.701695  0.483330
257             tobias harris -0.010116     -0.262543  0.792986
258                tony allen  0.008899      0.153741  0.877919
259               tony parker  0.032181      0.719122  0.472400
260                tony snell -0.047870     -0.634921  0.526314
261               travis wear -0.055441     -0.582226  0.561554
262              trevor ariza -0.015559     -0.400382  0.689015
263             trevor booker  0.051497      0.869069  0.385614
264                trey burke  0.013180      0.352386  0.724653
265          tristan thompson  0.072915      1.396964  0.163383
266                 ty lawson -0.033514     -0.873974  0.382449
267          tyler hansbrough  0.145398      1.070800  0.289728
268              tyler zeller  0.037646      0.732801  0.464170
269              tyreke evans -0.005573     -0.167650  0.866899
270            tyson chandler  0.016224      0.285429  0.775531
271             udonis haslem  0.048118      0.439675  0.661275
272            victor oladipo  0.025493      0.677847  0.498105
273              vince carter  0.014886      0.223997  0.822961
274           wayne ellington -0.057329     -1.127939  0.260069
275            wesley johnson  0.001743      0.035256  0.971893
276           wesley matthews -0.047961     -1.249311  0.211984
277           wilson chandler -0.052219     -1.395720  0.163266
278               zach lavine -0.016481     -0.298785  0.765306
279             zach randolph  0.049032      1.207406  0.227746
280             zaza pachulia -0.021562     -0.373902  0.708754

In [45]:
display(RegPlayer_WLS)

                 shoot_player      Coef  T_Statistics   P_Value
0                aaron brooks -0.017039     -0.379413  0.704547
1                aaron gordon -0.086933     -0.723936  0.471703
2             al farouq aminu  0.107612      1.706157  0.089587
3                  al horford  0.005338      0.142661  0.886602
4                al jefferson -0.042479     -1.176217  0.239888
5               alan anderson -0.023058     -0.388768  0.697757
6                 alan crabbe -0.001058     -0.008806  0.993008
7                    alex len  0.115282      1.852375  0.065253
8               alexis ajinca -0.025122     -0.310864  0.756317
9                  alonzo gee -0.353531     -3.607932  0.000507
10           amare stoudemire -0.032341     -0.573615  0.566681
11               amir johnson -0.039044     -0.745851  0.456285
12             andre drummond  0.088019      2.215923  0.027076
13             andre iguodala  0.043589      0.769536  0.442236
14               andre miller  0.090166      0.966586  0.335833
15             andre roberson -0.028382     -0.343689  0.731724
16               andrew bogut -0.026274     -0.386368  0.699668
17             andrew wiggins -0.011279     -0.312958  0.754402
18            anthony bennett -0.102395     -1.556199  0.121138
19              anthony davis  0.050995      1.482224  0.138685
20             anthony morrow -0.024418     -0.474343  0.635553
21                aron baynes -0.148635     -2.108450  0.036269
22              arron afflalo  0.009402      0.236519  0.813108
23              avery bradley  0.041344      1.114166  0.265599
24                 ben gordon  0.092587      1.287671  0.199379
25               ben mclemore  0.062801      1.474743  0.140899
26                 beno urdih -0.001357     -0.024314  0.980619
27            bismack biyombo -0.079393     -0.727560  0.469275
28              blake griffin  0.019422      0.580541  0.561707
29           bojan bogdanovic  0.078985      1.447283  0.148890
30                 boris diaw  0.034863      0.673837  0.500842
31               bradley beal -0.106795     -2.511158  0.012332
32               brandon bass  0.011914      0.242277  0.808687
33           brandon jennings -0.033315     -0.741394  0.458810
34             brandon knight -0.025514     -0.711580  0.476944
35              brian roberts  0.026195      0.454967  0.649461
36                brook lopez  0.044998      1.092338  0.275148
37                carl landry  0.041006      0.625330  0.532386
38              carlos boozer -0.059319     -1.422640  0.155406
39            carmelo anthony -0.053046     -1.464895  0.143374
40               caron butler -0.102197     -1.499966  0.135044
41           chandler parsons -0.017024     -0.424964  0.671014
42              channing frye -0.036301     -0.676278  0.499324
43         charlie villanueva  0.041488      0.532062  0.595311
44             chase budinger  0.135121      1.572001  0.118145
45             chris andersen -0.104146     -1.087543  0.279801
46                 chris bosh -0.045041     -1.192791  0.233361
47             chris copeland -0.104908     -1.761416  0.079376
48                chris kaman -0.033225     -0.650832  0.515561
49                 chris paul  0.013422      0.384144  0.700972
50                cj mccollum  0.130183      1.427027  0.156065
51                   cj miles -0.010084     -0.229610  0.818489
52                  cj watson  0.037190      0.592581  0.554001
53                cody zeller -0.012434     -0.216531  0.828729
54               cole aldrich  0.085467      1.052874  0.294174
55                cory joseph  0.078345      1.338652  0.181786
56               courtney lee  0.068832      1.409518  0.159449
57             damian lillard  0.042674      1.326649  0.184957
58               damjan rudez -0.026652     -0.320107  0.749386
59            danilo gallinai  0.036343      0.638843  0.523419
60                danny green  0.012346      0.276754  0.782088
61           dante cunningham  0.018852      0.269928  0.787507
62                 dante exum  0.014920      0.245317  0.806446
63             darrell arthur  0.024435      0.426144  0.670322
64            darren collison  0.020308      0.457215  0.647718
65                 david west -0.018660     -0.404963  0.685694
66             deandre jordan  0.008091      0.162221  0.871234
67           demarcus cousins  0.000830      0.023105  0.981573
68            demarre carroll -0.027477     -0.562354  0.574191
69            dennis schroder -0.041967     -0.845795  0.398192
70             deron williams  0.044785      0.972713  0.331211
71             derrick favors  0.006424      0.164208  0.869622
72               derrick rose  0.044429      1.202982  0.229381
73           derrick williams -0.038958     -0.627959  0.530659
74               devin harris  0.039452      0.774271  0.439282
75             dirk nowtizski -0.008459     -0.232595  0.816140
76                dj augustin -0.037120     -0.808199  0.419400
77               donald sloan  0.060251      1.065963  0.287340
78         donatas motiejunas -0.079889     -1.851785  0.064640
79             draymond green  0.026870      0.611018  0.541476
80                dwayne wade -0.000727     -0.019042  0.984813
81              dwight howard -0.021055     -0.383782  0.701419
82                   ed davis -0.023668     -0.426180  0.670303
83              elfrid payton  0.054199      1.109232  0.267987
84                enes kanter -0.053953     -1.357259  0.175234
85               eric bledsoe -0.025393     -0.695790  0.486791
86              evan fournier -0.132729     -3.036578  0.002521
87                evan turner -0.063982     -1.331829  0.183627
88             garrett temple  0.067934      0.713115  0.477244
89                  gary neal -0.046040     -0.937866  0.348883
90               gerald green -0.031336     -0.754816  0.450677
91           gerald henderson  0.029533      0.670785  0.502672
92      giannis antetokounmpo -0.025467     -0.581274  0.561331
93                 glen davis  0.000624      0.007425  0.994088
94               goran dragic -0.065251     -1.843475  0.065694
95             gordon hayward -0.034033     -0.975735  0.329492
96               gorgui dieng -0.059483     -1.112226  0.266834
97                greg monroe -0.014965     -0.391421  0.695616
98                 greg smith -0.086348     -0.238094  0.816616
99            greivis vasquez -0.059262     -1.322726  0.186570
100           harrison barnes  0.039098      0.808573  0.419250
101             hedo turkoglu  0.053791      0.472394  0.638449
102                henry sims  0.022947      0.431558  0.666327
103           hollis thompson  0.008926      0.151453  0.879727
104             isaiah thomas  0.017373      0.408636  0.682965
105            jakarr sampson -0.039540     -0.518977  0.604536
106            jamal crawford  0.020386      0.558953  0.576365
107               james ennis -0.040552     -0.403977  0.687043
108              james harden  0.043443      1.386370  0.165948
109             james johnson -0.019316     -0.334711  0.738124
110              jared dudley -0.073341     -1.290741  0.197825
111           jared sullinger -0.029715     -0.760089  0.447499
112              jarrett jack  0.004921      0.118834  0.905451
113             jason maxiell  0.021409      0.193405  0.847126
114               jason smith  0.117237      2.297321  0.022174
115               jason terry  0.043697      0.710567  0.477966
116            jason thompson  0.025080      0.391064  0.696125
117                jeff green  0.040395      1.067492  0.286149
118               jeff teague  0.025522      0.652085  0.514588
119              jerami grant  0.092578      1.172080  0.242886
120               jeremy lamb  0.133171      1.698296  0.091229
121                jeremy lin  0.080492      1.752594  0.080362
122             jerome jordan  0.117307      0.878939  0.383724
123            jerryd bayless  0.002071      0.038570  0.969256
124           jimmer dredette -0.026932     -0.282462  0.778162
125              jimmy butler -0.049547     -1.370485  0.170967
126                jj hickson -0.063632     -1.180647  0.238778
127                 jj redick  0.005187      0.126310  0.899531
128               joakim noah -0.074367     -1.255024  0.210528
129                joe harris -0.121468     -1.001741  0.320856
130               joe johnson -0.016368     -0.439770  0.660241
131               joey dorsey  0.408956      3.129900  0.003102
132               john henson -0.072886     -1.039247  0.300039
133                 john wall  0.001739      0.050268  0.959922
134                jon ingles -0.051224     -0.674588  0.500942
135                 jon leuer  0.078468      1.238816  0.216903
136             jonas jerebko -0.000639     -0.008319  0.993372
137         jonas valanciunas  0.005176      0.108380  0.913747
138             jordan farmar -0.126697     -1.304286  0.194834
139               jordan hill  0.005455      0.132486  0.894649
140             jose calderon  0.044887      0.785272  0.432929
141           jose juan barea -0.089440     -1.758077  0.079606
142              jrue holiday  0.021676      0.467671  0.640241
143              jusuf nurkic  0.133937      2.092654  0.037439
144             kawhi leonard  0.100421      2.213910  0.027323
145              kelly olynyk  0.041744      0.717179  0.473847
146              kemba walker -0.016572     -0.431528  0.666230
147          kendrick perkins -0.034768     -0.413487  0.679921
148            kenneth faried  0.095137      2.095893  0.036656
149             kent bazemore -0.079202     -1.043238  0.298562
150  kentavious caldwell-pope -0.004637     -0.116402  0.907373
151             kevin garnett -0.138186     -2.219823  0.027351
152                kevin love -0.051070     -1.366832  0.172117
153            kevin seraphin -0.056912     -0.970285  0.332779
154           khris middleton  0.010401      0.238615  0.811504
155              kirk hinrich -0.083095     -1.314065  0.190010
156              kj mcdaniels -0.060625     -1.179009  0.239193
157             klay thompson  0.006608      0.200290  0.841299
158               kobe bryant -0.006607     -0.172669  0.862964
159              kosta koufos -0.064464     -0.902551  0.367925
160       kostas papanikolaou  0.053051      0.692024  0.490093
161            kris humphries -0.003676     -0.067944  0.945872
162               kyle korver  0.016291      0.332319  0.739820
163                kyle lowry -0.021956     -0.640738  0.521875
164               kyle oquinn  0.001753      0.023220  0.981504
165              kyle singler -0.074231     -1.319325  0.188034
166              kyrie irving -0.030526     -0.900471  0.368118
167         lamarcus aldridge -0.001515     -0.048136  0.961617
168          lance stephenson -0.093985     -1.933706  0.053896
169               lavoy allen -0.010735     -0.169147  0.865853
170           leandro barbosa -0.077843     -1.187337  0.236503
171              lebron james -0.025388     -0.805055  0.420997
172              lou williams  0.022941      0.589025  0.556064
173          luc mbah a moute -0.063380     -1.396455  0.163305
174                luis scola -0.002061     -0.042818  0.965868
175              luke babbitt -0.019831     -0.209723  0.834298
176                 luol deng -0.072397     -1.684352  0.092735
177             manu ginobili  0.000295      0.006423  0.994879
178                marc gasol -0.110634     -3.062284  0.002276
179             marcin gortat  0.015356      0.369893  0.711620
180           marco belinelli  0.012355      0.202284  0.839847
181             marcus morris  0.044983      0.984619  0.325326
182              marcus smart  0.078262      1.288292  0.198870
183           marcus thornton -0.094141     -1.561568  0.119597
184            mario chalmers  0.046120      0.984487  0.325408
185           markieff morris  0.004778      0.133514  0.893822
186         marreese speights  0.047552      1.005462  0.315236
187           marvin williams -0.069683     -1.154290  0.249479
188             mason plumlee  0.099782      1.952877  0.051674
189               matt barnes -0.032529     -0.639535  0.522861
190               matt bonner  0.177888      2.138945  0.034163
191       matthew dellavedova -0.137541     -1.657290  0.099523
192   michael carter-williams  0.039856      1.017058  0.309537
193    michael kidd-gilchrist -0.085512     -1.567245  0.118058
194               mike conley -0.016430     -0.423517  0.672057
195               mike miller -0.009336     -0.066786  0.947013
196                mike scott  0.050583      0.906580  0.365364
197           mirza teletovic  0.015487      0.255504  0.798531
198                mnta ellis  0.019124      0.606426  0.544373
199               mo williams -0.076167     -1.740336  0.082414
200             nate robinson  0.128667      1.527855  0.128548
201              nene hilario -0.022705     -0.487585  0.626102
202               nerles noel -0.015422     -0.310962  0.756002
203             nick collison -0.044298     -0.573613  0.567089
204                nick young -0.080807     -1.707767  0.088420
205             nicolas batum  0.035710      0.725240  0.468744
206              nik stauskas  0.005009      0.060684  0.951702
207            nikola mirotic -0.041934     -0.751747  0.452807
208            nikola vucevic  0.007371      0.217514  0.827861
209               norris cole -0.019357     -0.347713  0.728299
210                   oj mayo -0.021816     -0.509816  0.610404
211                 omer asik -0.087789     -1.388306  0.166370
212               omri casspi -0.019463     -0.276348  0.782589
213               otto porter -0.030985     -0.463509  0.643460
214            pablo prigioni -0.092772     -1.011843  0.313683
215          patrick beverley -0.070673     -1.468267  0.142824
216         patrick patterson -0.019545     -0.359908  0.719144
217                 pau gasol -0.014917     -0.409263  0.682464
218              paul millsap -0.016744     -0.463642  0.643052
219               paul pierce -0.015090     -0.326266  0.744372
220                pero antic -0.035532     -0.468818  0.639819
221                 pj tucker -0.038053     -0.705746  0.480834
222                quincy acy -0.017420     -0.232131  0.816706
223            ramon sessions  0.025086      0.321458  0.748270
224             rasual butler -0.078685     -1.489845  0.137187
225              ray mccallum  0.084880      1.174159  0.241817
226            reggie jackson  0.128956      3.253832  0.001204
227         richard jefferson -0.097256     -1.326825  0.186285
228             robbie hummel  0.044533      0.390607  0.697152
229          robert covington  0.019691      0.433577  0.664804
230              robert sacre -0.067919     -0.971579  0.332564
231            rodney stuckey -0.053241     -1.190070  0.234616
232              ronnie price  0.124509      1.714455  0.088278
233               roy hibbert -0.128375     -2.804636  0.005250
234                  rudy gay  0.015558      0.456263  0.648323
235               rudy gobert  0.043029      0.638685  0.523766
236         russell westbrook -0.005913     -0.180421  0.856862
237             ryan anderson  0.012052      0.297901  0.765884
238               serge ibaka -0.010305     -0.271274  0.786265
239          shabazz muhammad -0.054620     -1.067761  0.286377
240            shabazz napier -0.093911     -1.183972  0.238260
241              shane larkin -0.115945     -1.747725  0.081953
242          shaun livingston  0.058318      0.842278  0.400654
243              shawn marion  0.039636      0.560067  0.576162
244           shawne williams -0.132089     -1.842065  0.067084
245              solomon hill -0.110091     -2.270703  0.023687
246             spencer hawes -0.078134     -1.286976  0.199209
247             stephen curry -0.083649     -2.557442  0.010708
248               steve adams  0.034023      0.509078  0.611227
249               steve blake  0.040688      0.550632  0.582588
250                taj gibson -0.010728     -0.208277  0.835131
251             terrence ross -0.014867     -0.333080  0.739216
252           thabo sefolosha  0.130293      1.646432  0.101797
253            thaddeus young -0.002213     -0.057035  0.954536
254                tim duncan  0.005901      0.142202  0.886972
255          time hardaway jr -0.054196     -1.266178  0.206011
256            timofey mozgov  0.076584      1.499346  0.134675
257             tobias harris -0.028958     -0.745420  0.456287
258                tony allen  0.024617      0.432553  0.665657
259               tony parker  0.049534      1.114995  0.265385
260                tony snell -0.037558     -0.490099  0.624681
261               travis wear -0.096653     -1.045452  0.298007
262              trevor ariza -0.021881     -0.570485  0.568558
263             trevor booker  0.037343      0.629745  0.529417
264                trey burke  0.022159      0.594193  0.552572
265          tristan thompson  0.079981      1.529815  0.127041
266                 ty lawson -0.007724     -0.200158  0.841418
267          tyler hansbrough  0.103294      0.760801  0.450576
268              tyler zeller  0.050204      0.977510  0.328992
269              tyreke evans -0.012497     -0.375857  0.707118
270            tyson chandler  0.002707      0.047457  0.962184
271             udonis haslem  0.021638      0.204263  0.838631
272            victor oladipo  0.029557      0.786419  0.431902
273              vince carter  0.001056      0.015712  0.987478
274           wayne ellington -0.069133     -1.372637  0.170688
275            wesley johnson -0.005992     -0.122406  0.902639
276           wesley matthews -0.024813     -0.643336  0.520225
277           wilson chandler -0.039111     -1.054474  0.292050
278               zach lavine -0.055391     -1.018136  0.309415
279             zach randolph  0.050400      1.246013  0.213240
280             zaza pachulia  0.002462      0.042237  0.966339

In [46]:
A_Wiggins_reg=Reg3_player(player_list[17])
print(A_Wiggins_reg.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.078
Model:                            OLS   Adj. R-squared:                  0.064
Method:                 Least Squares   F-statistic:                     5.602
Date:                Tue, 14 Apr 2026   Prob (F-statistic):           1.14e-08
Time:                        02:09:43   Log-Likelihood:                -500.04
No. Observations:                 738   AIC:                             1024.
Df Residuals:                     726   BIC:                             1079.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.2003      0.057      3.511      0.000       0.088       0.312
C(points)[T.3]       0.0726      0.069      1.053      0.293      -0.063       0.208
C(quarter)[T.2]      0.0087      0.051      0.171      0.865      -0.092       0.109
C(quarter)[T.3]      0.0029      0.048      0.061      0.951      -0.091       0.096
C(quarter)[T.4]      0.0320      0.051      0.624      0.533      -0.069       0.133
C(quarter)[T.5]     -0.1656      0.281     -0.589      0.556      -0.718       0.386
home_away[T.H]       0.0233      0.036      0.647      0.518      -0.047       0.094
lagerror            -0.0016      0.036     -0.044      0.965      -0.072       0.069
shot_dist           -0.0212      0.003     -6.769      0.000      -0.027      -0.015
dribbles            -0.0095      0.017     -0.546      0.585      -0.044       0.025
touch_time          -0.0129      0.018     -0.733      0.464      -0.047       0.022
closest_def_dist     0.0206      0.009      2.384      0.017       0.004       0.038
==============================================================================
Omnibus:                     4176.254   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               89.399
Skew:                           0.260   Prob(JB):                     3.87e-20
Kurtosis:                       1.376   Cond. No.                         241.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [47]:
J_Harden_reg=Reg3_player(player_list[108])
print(J_Harden_reg.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.053
Model:                            OLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     4.952
Date:                Tue, 14 Apr 2026   Prob (F-statistic):           1.61e-07
Time:                        02:11:20   Log-Likelihood:                -691.15
No. Observations:                 995   AIC:                             1406.
Df Residuals:                     983   BIC:                             1465.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.1003      0.053      1.902      0.058      -0.003       0.204
C(points)[T.3]       0.0715      0.061      1.179      0.239      -0.048       0.191
C(quarter)[T.2]      0.0061      0.045      0.134      0.894      -0.083       0.095
C(quarter)[T.3]     -0.0207      0.042     -0.494      0.622      -0.103       0.062
C(quarter)[T.4]      0.0091      0.048      0.192      0.848      -0.084       0.102
C(quarter)[T.5]      0.1730      0.159      1.085      0.278      -0.140       0.486
home_away[T.H]       0.0023      0.032      0.070      0.944      -0.060       0.065
lagerror             0.0257      0.031      0.821      0.412      -0.036       0.087
shot_dist           -0.0154      0.003     -4.754      0.000      -0.022      -0.009
dribbles             0.0103      0.008      1.224      0.221      -0.006       0.027
touch_time          -0.0127      0.010     -1.294      0.196      -0.032       0.007
closest_def_dist     0.0341      0.008      4.016      0.000       0.017       0.051
==============================================================================
Omnibus:                     4449.293   Durbin-Watson:                   2.022
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              136.371
Skew:                           0.188   Prob(JB):                     2.44e-30
Kurtosis:                       1.226   Cond. No.                         201.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [48]:
S_Curry_reg=Reg3_player(player_list[247])
print(S_Curry_reg.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.074
Model:                            OLS   Adj. R-squared:                  0.062
Method:                 Least Squares   F-statistic:                     6.498
Date:                Tue, 14 Apr 2026   Prob (F-statistic):           1.79e-10
Time:                        02:12:54   Log-Likelihood:                -625.19
No. Observations:                 910   AIC:                             1274.
Df Residuals:                     898   BIC:                             1332.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.2196      0.057      3.867      0.000       0.108       0.331
C(points)[T.3]       0.1007      0.055      1.818      0.069      -0.008       0.210
C(quarter)[T.2]     -0.0474      0.048     -0.997      0.319      -0.141       0.046
C(quarter)[T.3]     -0.0445      0.042     -1.064      0.288      -0.126       0.038
C(quarter)[T.4]     -0.0776      0.047     -1.641      0.101      -0.170       0.015
C(quarter)[T.5]      0.0963      0.202      0.476      0.634      -0.301       0.493
home_away[T.H]       0.0078      0.033      0.238      0.812      -0.056       0.072
lagerror            -0.0607      0.033     -1.862      0.063      -0.125       0.003
shot_dist           -0.0181      0.003     -6.101      0.000      -0.024      -0.012
dribbles             0.0139      0.013      1.082      0.280      -0.011       0.039
touch_time          -0.0196      0.016     -1.239      0.216      -0.051       0.011
closest_def_dist     0.0238      0.006      3.712      0.000       0.011       0.036
==============================================================================
Omnibus:                     4325.364   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              113.453
Skew:                           0.064   Prob(JB):                     2.31e-25
Kurtosis:                       1.275   Cond. No.                         263.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [49]:
R_Westbrook_reg=Reg3_player(player_list[236])
print(R_Westbrook_reg.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  error   R-squared:                       0.063
Model:                            OLS   Adj. R-squared:                  0.051
Method:                 Least Squares   F-statistic:                     5.529
Date:                Tue, 14 Apr 2026   Prob (F-statistic):           1.32e-08
Time:                        02:14:48   Log-Likelihood:                -631.81
No. Observations:                 923   AIC:                             1288.
Df Residuals:                     911   BIC:                             1346.
Df Model:                          11
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.0958      0.051      1.893      0.059      -0.004       0.195
C(points)[T.3]      -0.0138      0.060     -0.232      0.817      -0.131       0.103
C(quarter)[T.2]     -0.0034      0.046     -0.075      0.940      -0.093       0.086
C(quarter)[T.3]     -0.0061      0.043     -0.141      0.888      -0.091       0.078
C(quarter)[T.4]      0.0114      0.047      0.241      0.810      -0.081       0.104
C(quarter)[T.5]      0.1294      0.113      1.145      0.253      -0.093       0.351
home_away[T.H]       0.0319      0.032      0.984      0.325      -0.032       0.095
lagerror            -0.0090      0.033     -0.275      0.783      -0.073       0.055
shot_dist           -0.0148      0.003     -5.353      0.000      -0.020      -0.009
dribbles            -0.0119      0.011     -1.121      0.263      -0.033       0.009
touch_time           0.0120      0.013      0.959      0.338      -0.013       0.037
closest_def_dist     0.0207      0.006      3.449      0.001       0.009       0.032
==============================================================================
Omnibus:                     4411.123   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              124.183
Skew:                           0.259   Prob(JB):                     1.08e-27
Kurtosis:                       1.279   Cond. No.                         123.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.